apiVersion: 1

datasources:
  - name: QuestDB
    uid: questdb
    type: postgres
    access: proxy
    url: questdb:8812
    user: admin
    database: qdb
    jsonData:
      postgresVersion: 1500
      sslmode: disable
      timescaledb: false
    secureJsonData:
      password: quest
